- name: create an access token
  uri:
      url: "https://{{ datasentinel_host }}/ds-api/user-token"
      method: POST
      user: "{{ datasentinel_user }}"
      password: "{{ datasentinel_password }}"
      return_content: yes
      force_basic_auth: yes
      validate_certs: False
      status_code: 201
  register: access_token
  tags: always

- name: register the token to user_token variable
  set_fact:
    user_token: "{{ access_token['json']['user-token'] }}"
  tags: always

- name: display the token
  debug:
    var: user_token
  tags: always

- name: Get token  properties
  uri:
      url: "https://{{ datasentinel_host }}/ds-api/user-token?token={{ user_token }}"
      method: GET
      return_content: yes
      validate_certs: False
      status_code: 200
  register: access_token
  tags: always

- name: display the token properties
  debug:
    var: access_token.json
  tags: always