version: '2.2'
volumes:
  pg_data:
  influx_data:
  nginx_certs:
services:
  postgresql:
    image: datasentinel-postgres
    container_name: datasentinel-postgres
    restart: always
    networks:
        - datasentinel
    volumes:
        - pg_data:/var/lib/postgresql/data
  grafana:
    image: datasentinel-grafana
    container_name: datasentinel-grafana
    networks:
        - datasentinel
    depends_on:
      postgresql:
        condition: service_started
    restart: always
  influxdb:
    image: datasentinel-influxdb
    container_name: datasentinel-influxdb
    restart: always
    networks:
        - datasentinel
    volumes:
        - influx_data:/var/lib/influxdb
  backend:
    image: datasentinel-backend
    container_name: datasentinel-backend
    depends_on:
      influxdb:
        condition: service_started
    networks:
        - datasentinel
    restart: always
  nginx:
    image: datasentinel-nginx
    container_name: datasentinel-nginx
    depends_on:
      backend:
        condition: service_started
      grafana:
        condition: service_started
    restart: always
    networks:
        - datasentinel
    volumes:
        - nginx_certs:/etc/nginx/certs
    ports:
        - 8080:80
        - 4443:443
networks:
    datasentinel:
        driver: bridge