apiVersion: v1
kind: Service
metadata:
  name: datasentinel-agent
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: datasentinel-agent
  ports:
  - protocol: TCP
    port: 8384
    targetPort: 8384